site_name: Transformation Flow
site_url: https://transformationflow.io/

# Repository
repo_name: transformationflow/transformationflow.github.io
repo_url: https://github.com/transformationflow/transformationflow.github.io

theme:
  name: material
  font:
    text: Monserrat
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
      primary: white
      accent:  blue grey 
    - scheme: slate 
      toggle:
        icon: material/weather-night 
        name: Switch to light mode    
      primary: black
      accent: cyan
  icon:
    repo: fontawesome/brands/github
  logo: assets/logos/TransformationFlowLogo3DTransparent.png
  favicon: assets/logos/TransformationFlowLogo3DTransparent_100x100.png

  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.integrate

plugins:
  - search

nav:
  - Introduction: index.md
  - Libraries: libraries.md
  - Reference:
    - Terminology: reference/terminology.md

    - BigQuery Tools:
      - Introduction: reference/bqtools/index.md
      - Resources:
        - CREATE: reference/bqtools/resources/create.md

    - BigQuery Manager:
      - Introduction: reference/bqmanager/index.md

    - Decode Data:
      - Introduction: reference/decodedata/index.md
      - Overview: reference/decodedata/overview.md
      - Resources:
        - Deployment: reference/decodedata/resources/deployment.md

  #    - Resources:
  #      - Metadata: reference/bqtools/resources/metadata.md
  #      - Create: reference/bqtools/resources/create.md
  #      - Copy: reference/bqtools/resources/copy.md
  #    - Partitions:
  #      - Partitioned Tables: reference/bqtools/partitions/partitioning.md
  #      - Sharded Tables: reference/bqtools/partitions/sharding.md
  #    - Queries:
  #      - Profiling: reference/bqtools/queries/profiling.md
  #      - Manipulation: reference/bqtools/queries/manipulation.md
  #    - Data:
  #      - Manipulation: reference/bqtools/data/manipulation.md
  #      - Decoders: reference/bqtools/data/decoders.md
  #      - Export: reference/bqtools/data/export.md
  #    - Types:
  #      - Dates: reference/bqtools/types/dates.md
  #      - Strings: reference/bqtools/types/strings.md
  #      - Arrays: reference/bqtools/types/arrays.md
  #    - Objects:
  #      - Profiling: reference/bqtools/objects/profiling.md

 
    #   - Resources: reference/bqmanager/resources.md
    #   - Definitions:
    #     - Configuration: reference/bqmanager/configuration.md
    #     - Common Arguments: reference/bqmanager/arguments.md
      # - Information Schema: reference/bqmanager/information_schema.md
    

    #  - Event Profiling: reference/decodedata-ga4/profiling.md


  - Publications:
    - Medium: publications/medium.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight   
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - meta
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - toc:
      baselevel: 2
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  analytics:
    provider: google
    property: G-2SWKZ494KD

  social:
    - icon: fontawesome/brands/medium
      link: https://jim-barlow.medium.com/
    - icon: fontawesome/brands/github
      link: https://github.com/transformationflow   
    - icon: fontawesome/solid/paper-plane
      link: mailto:hello@transformationflow.io
    - icon: fontawesome/solid/calendar
      link: https://calendly.com/transformationflow/15

#extra_css:
#  - stylesheets/extra.css

#extra_javascript:
#  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
#  - javascripts/tables.js

copyright: Copyright &copy; 2023 Transformationflow OÜ (16248096), Estonia