site_name: Transformation Flow
# repo_url: https://github.com/transformationflow/txflow

theme:
  name: material
  font:
    text: Monserrat
  palette:
    primary: teal
    accent: cyan
  logo: assets/TxFlow_Geometric_Logo_Icon_White_on_Transparent.png
  favicon: assets/TxFlow_Geometric_Logo_Icon_100x100.png
  
  #icon:
  #  repo: fontawesome/brands/git-alt  
  
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.instant

nav:
  - Intro:

    - Introduction: 'index.md'
    - Principles: 'the-zen-of-sql.md'
    - Philosophy: 'context.md'
  
  - Documentation:
    - Style Guide: 'documentation/style-guide.md'
    - Key Concepts: 'documentation/concepts.md'
    - Architecture: 'documentation/architecture.md'
    - Data Ingestion: 'documentation/ingestion.md'
    
    #- Use Cases:
      #- Data Backup: 'documentation/usecases/backup.md'
    
    - Functions:
      - SQL Builder Functions: 'documentation/functions/sqlbuilders.md'
      # - Flow Functions: 'documentation/functions/flowfunctions.md'
      - Remote Functions: 'documentation/functions/remotefunctions.md'

markdown_extensions:
  - admonition
  - pymdownx.highlight   
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - meta
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      baselevel: 2
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  analytics:
    provider: google
    property: G-2SWKZ494KD

  social:
    - icon: fontawesome/brands/medium
      link: https://jim-barlow.medium.com/
    - icon: fontawesome/brands/github
      link: https://github.com/transformationflow   
    - icon: fontawesome/solid/paper-plane
      link: mailto:jim@transformationflow.io

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

#plugins:
#  - git-revision-date-localized:
#      enable_creation_date: true

copyright: Copyright &copy; 2022 Transformationflow OÜ (16248096), Estonia