site_name: Transformation Flow

theme:
  name: material
  font:
    text: Monserrat
  palette:
    primary: teal
    accent: cyan
  logo: assets/TxFlow_Geometric_Logo_Icon_White_on_Transparent.png
  favicon: assets/TxFlow_Geometric_Logo_Icon_100x100.png
    
nav:
  - Welcome: 'index.md'
  # - About Us: 'about-us.md'
  #- 'Flow Stages':
  #    - Data Ingestion: 'stages-ingestion.md'
  #    - Data Profiling: 'stages-profiling.md'
  #    - Data Transformation: 'stages-transformation.md'
      # - Data Profiling: 
      #  Ingest: 'reference_functions.md'
  - 'Functions':
      - Overview: 'functions-overview.md'
      #- Data Ingestion: 'functions-ingestion.md'
      #- Prepare: 'functions-preparation.md'
      #- Transform: 'functions-transformation.md'

  #- 'Utility Functions':
  #    - Overview: 'utils--overview.md'
      #- String: 'utils-string.md'
      #- JSON: 'utils-json.md'
      #- Data Visualisation: 'utils-dataviz.md'

  #- 'Reference':
      #- Action Codes: 'reference-transformation-codes.md'
    

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js