site_name: Transformation Flow
# repo_url: https://github.com/transformationflow/txflow

theme:
  name: material
  font:
    text: Monserrat
  palette:
    primary: teal
    accent: cyan
  logo: assets/TxFlow_Geometric_Logo_Icon_White_on_Transparent.png
  favicon: assets/TxFlow_Geometric_Logo_Icon_100x100.png
  
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.instant

nav:
  - Introduction: index.md
  - Products: products.md
  - Reference:
    # - reference/methodology.md
    - BigQuery Tools (bqtools): reference/bqtools.md
    - BigQuery Manager: reference/bqmanager.md
    - Decode Data for GA4: reference/decodedata.md

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight   
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - meta
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      baselevel: 2
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  analytics:
    provider: google
    property: G-2SWKZ494KD

  social:
    - icon: fontawesome/brands/medium
      link: https://jim-barlow.medium.com/
    - icon: fontawesome/brands/github
      link: https://github.com/transformationflow   
    - icon: fontawesome/solid/paper-plane
      link: mailto:hello@transformationflow.io

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

copyright: Copyright &copy; 2023 Transformationflow OÜ (16248096), Estonia