site_name: Transformation Flow
# repo_url: https://github.com/transformationflow/txflow

theme:
  name: material
  font:
    text: Monserrat
  palette:
    primary: teal
    accent: cyan
  logo: assets/TxFlow_Geometric_Logo_Icon_White_on_Transparent.png
  favicon: assets/TxFlow_Geometric_Logo_Icon_100x100.png
  
  #icon:
  #  repo: fontawesome/brands/git-alt  
  
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top  
    
nav:
  - Overview: 'index.md'
  - Philosophy: 'the-zen-of-sql.md' 
  - Context: 'context.md'
  # - Considerations: 'considerations.md'
  - Style Guide: 'style-guide.md'
  # - Consulting: 'consulting.md'
  # - Guides:
  #   - CSV Ingestion: 'csv-ingestion.md'
  #   - Schema Alignment: 'schema-alignment.md'
  
  # - Quickstart: 'quickstart.md'
  
  
  # - flowfunctions: 'flowfunctions.md'
  
  # - Framework: 'framework.md'
  # - How to Write SQL: 'how-to-write-sql.md'
  # - Workflow: 'workflow.md'
  # - Functions: 'overview-functions.md'
  # - Getting Started: 'getting-started.md'

markdown_extensions:
  - admonition
  - pymdownx.highlight   
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - meta
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      baselevel: 2
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  analytics:
    provider: google
    property: G-2SWKZ494KD

  social:
    - icon: fontawesome/brands/medium
      link: https://jimbeepbeep.medium.com/
    - icon: fontawesome/brands/github
      link: https://github.com/jimbeepbeep   
    - icon: fontawesome/solid/paper-plane
      link: mailto:jim@transformationflow.io


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

plugins:
  # - git-revision-date

copyright: Copyright &copy; 2021 Transformationflow OÜ (16248096), Estonia
