site_name: Transformation Flow

theme:
  name: material
  font:
    text: Monserrat
  palette:
    primary: teal
    accent: cyan
    
nav:
  - Welcome: 'index.md'
  - About Us: 'about-us.md'
  - 'Reference':
    - Action Codes: 'reference_codes.md'
    - Functions: 'reference_functions.md'

markdown_extensions:
  - admonition

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js