site_name: Transformation Flow
repo_url: https://github.com/transformationflow/txflow

theme:
  name: material
  font:
    text: Monserrat
  palette:
    primary: teal
    accent: cyan
  logo: assets/TxFlow_Geometric_Logo_Icon_White_on_Transparent.png
  favicon: assets/TxFlow_Geometric_Logo_Icon_100x100.png
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.top
  icon:
    repo: fontawesome/brands/git-alt    
    
nav:
  - Overview: 'index.md'
  #- Overview: 'overview-all.md'
  #- 'Approach':
  - Philosophy: 'the-zen-of-sql.md' 
  - Functions: 'overview-functions.md'
  #- 
  #  - Overview: 'overview-methodology.md'    

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - footnotes
  - meta
  - toc:
      baselevel: 2
      
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

copyright: Copyright &copy; 2021 Transformationflow OÜ (16248096), Estonia
