site_name: Transformation Flow
site_url: https://transformationflow.io/

theme:
  name: material
  font:
    text: Monserrat
  palette:
    primary: teal
    accent: cyan
  logo: assets/TxFlow_Geometric_Logo_Icon_White_on_Transparent.png
  favicon: assets/TxFlow_Geometric_Logo_Icon_100x100.png
  
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.integrate

plugins:
  - search

nav:
  - Introduction: index.md
  - Products: products.md
  - Reference:
    - Glossary: reference/glossary.md

    - BigQuery Tools:
      - Overview: reference/bqtools/index.md
      - Resources:
        - Metadata: reference/bqtools/metadata.md
        - Creation: reference/bqtools/creation.md
        - Replication: reference/bqtools/replication.md
      - Partitions:
        - Partitioned Tables: reference/bqtools/partitioning.md
        - Sharded Tables: reference/bqtools/sharding.md
      - Queries:
        - Interaction: reference/bqtools/query.md
      - Data:
        - String: reference/bqtools/string.md
        - Array: reference/bqtools/array.md
        - Decoding: reference/bqtools/decoders.md
        - Interaction: reference/bqtools/data.md

    - BigQuery Manager:
      - Overview: reference/bqmanager/index.md
      - Information Schema: reference/bqmanager/information_schema.md
    
    - Decode Data for GA4:
      - Overview: reference/decodedata-ga4/index.md
      - Event Profiler: reference/decodedata-ga4/profiler.md

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight   
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - meta
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - toc:
      baselevel: 2
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  analytics:
    provider: google
    property: G-2SWKZ494KD

  social:
    - icon: fontawesome/brands/medium
      link: https://jim-barlow.medium.com/
    - icon: fontawesome/brands/github
      link: https://github.com/transformationflow   
    - icon: fontawesome/solid/paper-plane
      link: mailto:hello@transformationflow.io

#extra_css:
#  - stylesheets/extra.css

#extra_javascript:
#  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
#  - javascripts/tables.js

copyright: Copyright &copy; 2023 Transformationflow OÜ (16248096), Estonia