site_name: Transformation Flow
# repo_url: https://github.com/transformationflow/txflow

theme:
  name: material
  font:
    text: Monserrat
  palette:
    primary: teal
    accent: cyan
  logo: assets/TxFlow_Geometric_Logo_Icon_White_on_Transparent.png
  favicon: assets/TxFlow_Geometric_Logo_Icon_100x100.png
  
  #icon:
  #  repo: fontawesome/brands/git-alt  
  
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top  
    
nav:
  - Overview: 'index.md'
  - Philosophy: 'the-zen-of-sql.md' 
  # - How to Write SQL: 'how-to-write-sql.md'
  # - Workflow: 'workflow.md'
  # - Functions: 'overview-functions.md'
  # - Getting Started: 'getting-started.md'

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - footnotes
  - meta
  - toc:
      baselevel: 2

extra:
  analytics:
    provider: google
    property: G-P2ZCF8ZKFD

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

plugins:
  # - git-revision-date

copyright: Copyright &copy; 2021 Transformationflow OÜ (16248096), Estonia
